name: Release

# Create a release on a tag push event
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Basic java run
    uses: ./.github/workflows/base.yaml
    with:
      use-snapshots: false
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
